kind: pipeline
type: docker
name: webpage

steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - npm install
      - npm run build
      - cp ./build -R /tmp/cache

volumes:
- name: cache
  host:
    path: /data
