kind: pipeline
type: docker
name: webpage

steps:
  - name: build
    when:
      branch:
        - publish
    image: node
volumes:
  - name: cache
    path: /tmp/cache
    commands:
      - npm install
      - npm run build
      - cp ./build /runner/webpage

volumes:
- name: cache
  host:
    path: /var/lib/cache
